"""
title_and_desc.py — given the winner candidate + music spec + brief, ask Kimi
for a YouTube-style title and description. Outputs metadata.json.

Usage:
    python title_and_desc.py --winner winner.json --music spec.json \
        --brief "..." --out metadata.json
"""
import argparse
import json
from pathlib import Path
from datetime import datetime

from kimi_client import chat_json

SYSTEM = """You write titles and descriptions for short experimental video
art pieces. Style is terse, technical, media-art register — no hype, no
emojis, no clickbait. Match the format below exactly.

Return strict JSON:
{
  "title":       "<short title in the form: PV<NNN> — <2-4 word name>>",
  "yt_title":    "<one-line YouTube title under 70 chars, descriptive not hype>",
  "description": "<2-4 paragraph terse description of the piece, attribution to public-domain source, brief technical pipeline note>",
  "hashtags":    ["#generativeart", "#newmedia", "#creativecoding"]
}

The piece always ends with a date stamp YYYYMMDD on the first line of the
'description' field, plus the full title on the second line, followed by the
prose body.
"""

USER_TPL = """Brief: {brief}

Source video used: "{source_title}" ({source_year}, Internet Archive item
{source_id}, public domain). URL: {source_url}

Music spec: {music_key} {music_mode}, {music_bpm} BPM, mood: {music_mood}.

The piece is 26 seconds, dual-format (16:9 + 9:16), generated by an
audio-reactive blob-tracking + glitch pipeline (OpenCV + numpy + librosa,
Python ambient synth). Theme tag: "Machine Vision for the Public Domain".

Date: {date_yyyymmdd}
PV slug: {slug}

Return JSON only."""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--winner", required=True)
    ap.add_argument("--music", required=True, help="music spec.json")
    ap.add_argument("--brief", required=True)
    ap.add_argument("--slug", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    w = json.loads(Path(args.winner).read_text())
    m = json.loads(Path(args.music).read_text())
    today = datetime.now().strftime("%Y%m%d")

    user = USER_TPL.format(
        brief=args.brief,
        source_title=w.get("title", ""),
        source_year=w.get("year", ""),
        source_id=w.get("identifier", ""),
        source_url=w.get("url", ""),
        music_key=m.get("key", ""),
        music_mode=m.get("mode", ""),
        music_bpm=m.get("bpm", ""),
        music_mood=m.get("mood", ""),
        date_yyyymmdd=today,
        slug=args.slug,
    )

    data = chat_json(SYSTEM, user, temperature=0.5, max_tokens=600)

    out = {
        "slug": args.slug,
        "date": today,
        "brief": args.brief,
        "source": {
            "identifier": w.get("identifier"),
            "title": w.get("title"),
            "year": w.get("year"),
            "url": w.get("url"),
        },
        "music": m,
        "kimi": data,
    }
    Path(args.out).write_text(json.dumps(out, indent=2))
    print(f"wrote {args.out}")
    print("---")
    print("title:    ", data.get("title"))
    print("yt_title: ", data.get("yt_title"))
    print("---")
    print(data.get("description", ""))


if __name__ == "__main__":
    main()
